/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.twelve.capital.greetings.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the GreetingsMessage service. Represents a row in the &quot;greetings_GreetingsMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.twelve.capital.greetings.service.model.impl.GreetingsMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.twelve.capital.greetings.service.model.impl.GreetingsMessageImpl}.
 * </p>
 *
 * @author neha.kakkar
 * @see GreetingsMessage
 * @see com.twelve.capital.greetings.service.model.impl.GreetingsMessageImpl
 * @see com.twelve.capital.greetings.service.model.impl.GreetingsMessageModelImpl
 * @generated
 */
public interface GreetingsMessageModel extends BaseModel<GreetingsMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a greetings message model instance should use the {@link GreetingsMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this greetings message.
	 *
	 * @return the primary key of this greetings message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this greetings message.
	 *
	 * @param primaryKey the primary key of this greetings message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the status ID of this greetings message.
	 *
	 * @return the status ID of this greetings message
	 */
	public long getStatusId();

	/**
	 * Sets the status ID of this greetings message.
	 *
	 * @param StatusId the status ID of this greetings message
	 */
	public void setStatusId(long StatusId);

	/**
	 * Returns the message of this greetings message.
	 *
	 * @return the message of this greetings message
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this greetings message.
	 *
	 * @param Message the message of this greetings message
	 */
	public void setMessage(String Message);

	/**
	 * Returns the button_color of this greetings message.
	 *
	 * @return the button_color of this greetings message
	 */
	@AutoEscape
	public String getButton_color();

	/**
	 * Sets the button_color of this greetings message.
	 *
	 * @param button_color the button_color of this greetings message
	 */
	public void setButton_color(String button_color);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GreetingsMessage greetingsMessage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GreetingsMessage> toCacheModel();

	@Override
	public GreetingsMessage toEscapedModel();

	@Override
	public GreetingsMessage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}