/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.twelve.capital.greetings.service.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.twelve.capital.greetings.service.model.User_Status;
import com.twelve.capital.greetings.service.service.User_StatusLocalServiceUtil;

/**
 * The extended model base implementation for the User_Status service. Represents a row in the &quot;greetings_User_Status&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link User_StatusImpl}.
 * </p>
 *
 * @author neha.kakkar
 * @see User_StatusImpl
 * @see com.twelve.capital.greetings.service.model.User_Status
 * @generated
 */
public abstract class User_StatusBaseImpl extends User_StatusModelImpl
	implements User_Status {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user_ status model instance should use the {@link User_Status} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			User_StatusLocalServiceUtil.addUser_Status(this);
		}
		else {
			User_StatusLocalServiceUtil.updateUser_Status(this);
		}
	}
}