/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.twelve.capital.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import com.twelve.capital.model.adminalert;
import com.twelve.capital.service.adminalertLocalService;
import com.twelve.capital.service.persistence.adminalertPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the adminalert local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.twelve.capital.service.impl.adminalertLocalServiceImpl}.
 * </p>
 *
 * @author neha.kakkar
 * @see com.twelve.capital.service.impl.adminalertLocalServiceImpl
 * @see com.twelve.capital.service.adminalertLocalServiceUtil
 * @generated
 */
public abstract class adminalertLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements adminalertLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.twelve.capital.service.adminalertLocalServiceUtil} to access the adminalert local service.
	 */

	/**
	 * Adds the adminalert to the database. Also notifies the appropriate model listeners.
	 *
	 * @param adminalert the adminalert
	 * @return the adminalert that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public adminalert addadminalert(adminalert adminalert)
		throws SystemException {
		adminalert.setNew(true);

		return adminalertPersistence.update(adminalert);
	}

	/**
	 * Creates a new adminalert with the primary key. Does not add the adminalert to the database.
	 *
	 * @param alertId the primary key for the new adminalert
	 * @return the new adminalert
	 */
	@Override
	public adminalert createadminalert(long alertId) {
		return adminalertPersistence.create(alertId);
	}

	/**
	 * Deletes the adminalert with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param alertId the primary key of the adminalert
	 * @return the adminalert that was removed
	 * @throws PortalException if a adminalert with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public adminalert deleteadminalert(long alertId)
		throws PortalException, SystemException {
		return adminalertPersistence.remove(alertId);
	}

	/**
	 * Deletes the adminalert from the database. Also notifies the appropriate model listeners.
	 *
	 * @param adminalert the adminalert
	 * @return the adminalert that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public adminalert deleteadminalert(adminalert adminalert)
		throws SystemException {
		return adminalertPersistence.remove(adminalert);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(adminalert.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return adminalertPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.twelve.capital.model.impl.adminalertModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return adminalertPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.twelve.capital.model.impl.adminalertModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return adminalertPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return adminalertPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return adminalertPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public adminalert fetchadminalert(long alertId) throws SystemException {
		return adminalertPersistence.fetchByPrimaryKey(alertId);
	}

	/**
	 * Returns the adminalert with the primary key.
	 *
	 * @param alertId the primary key of the adminalert
	 * @return the adminalert
	 * @throws PortalException if a adminalert with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public adminalert getadminalert(long alertId)
		throws PortalException, SystemException {
		return adminalertPersistence.findByPrimaryKey(alertId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return adminalertPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the adminalerts.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.twelve.capital.model.impl.adminalertModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of adminalerts
	 * @param end the upper bound of the range of adminalerts (not inclusive)
	 * @return the range of adminalerts
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<adminalert> getadminalerts(int start, int end)
		throws SystemException {
		return adminalertPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of adminalerts.
	 *
	 * @return the number of adminalerts
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getadminalertsCount() throws SystemException {
		return adminalertPersistence.countAll();
	}

	/**
	 * Updates the adminalert in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param adminalert the adminalert
	 * @return the adminalert that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public adminalert updateadminalert(adminalert adminalert)
		throws SystemException {
		return adminalertPersistence.update(adminalert);
	}

	/**
	 * Returns the adminalert local service.
	 *
	 * @return the adminalert local service
	 */
	public com.twelve.capital.service.adminalertLocalService getadminalertLocalService() {
		return adminalertLocalService;
	}

	/**
	 * Sets the adminalert local service.
	 *
	 * @param adminalertLocalService the adminalert local service
	 */
	public void setadminalertLocalService(
		com.twelve.capital.service.adminalertLocalService adminalertLocalService) {
		this.adminalertLocalService = adminalertLocalService;
	}

	/**
	 * Returns the adminalert remote service.
	 *
	 * @return the adminalert remote service
	 */
	public com.twelve.capital.service.adminalertService getadminalertService() {
		return adminalertService;
	}

	/**
	 * Sets the adminalert remote service.
	 *
	 * @param adminalertService the adminalert remote service
	 */
	public void setadminalertService(
		com.twelve.capital.service.adminalertService adminalertService) {
		this.adminalertService = adminalertService;
	}

	/**
	 * Returns the adminalert persistence.
	 *
	 * @return the adminalert persistence
	 */
	public adminalertPersistence getadminalertPersistence() {
		return adminalertPersistence;
	}

	/**
	 * Sets the adminalert persistence.
	 *
	 * @param adminalertPersistence the adminalert persistence
	 */
	public void setadminalertPersistence(
		adminalertPersistence adminalertPersistence) {
		this.adminalertPersistence = adminalertPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.twelve.capital.model.adminalert",
			adminalertLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.twelve.capital.model.adminalert");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return adminalert.class;
	}

	protected String getModelClassName() {
		return adminalert.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = adminalertPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.twelve.capital.service.adminalertLocalService.class)
	protected com.twelve.capital.service.adminalertLocalService adminalertLocalService;
	@BeanReference(type = com.twelve.capital.service.adminalertService.class)
	protected com.twelve.capital.service.adminalertService adminalertService;
	@BeanReference(type = adminalertPersistence.class)
	protected adminalertPersistence adminalertPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private adminalertLocalServiceClpInvoker _clpInvoker = new adminalertLocalServiceClpInvoker();
}