/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.twelve.capital.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the adminalert service. Represents a row in the &quot;aa_adminalert&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.twelve.capital.model.impl.adminalertModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.twelve.capital.model.impl.adminalertImpl}.
 * </p>
 *
 * @author neha.kakkar
 * @see adminalert
 * @see com.twelve.capital.model.impl.adminalertImpl
 * @see com.twelve.capital.model.impl.adminalertModelImpl
 * @generated
 */
public interface adminalertModel extends BaseModel<adminalert> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a adminalert model instance should use the {@link adminalert} interface instead.
	 */

	/**
	 * Returns the primary key of this adminalert.
	 *
	 * @return the primary key of this adminalert
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this adminalert.
	 *
	 * @param primaryKey the primary key of this adminalert
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the alert ID of this adminalert.
	 *
	 * @return the alert ID of this adminalert
	 */
	public long getAlertId();

	/**
	 * Sets the alert ID of this adminalert.
	 *
	 * @param alertId the alert ID of this adminalert
	 */
	public void setAlertId(long alertId);

	/**
	 * Returns the group ID of this adminalert.
	 *
	 * @return the group ID of this adminalert
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this adminalert.
	 *
	 * @param groupId the group ID of this adminalert
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this adminalert.
	 *
	 * @return the create date of this adminalert
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this adminalert.
	 *
	 * @param createDate the create date of this adminalert
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this adminalert.
	 *
	 * @return the modified date of this adminalert
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this adminalert.
	 *
	 * @param modifiedDate the modified date of this adminalert
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the location of this adminalert.
	 *
	 * @return the location of this adminalert
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this adminalert.
	 *
	 * @param location the location of this adminalert
	 */
	public void setLocation(String location);

	/**
	 * Returns the resolution of this adminalert.
	 *
	 * @return the resolution of this adminalert
	 */
	@AutoEscape
	public String getResolution();

	/**
	 * Sets the resolution of this adminalert.
	 *
	 * @param resolution the resolution of this adminalert
	 */
	public void setResolution(String resolution);

	/**
	 * Returns the expected resolution time of this adminalert.
	 *
	 * @return the expected resolution time of this adminalert
	 */
	public Date getExpectedResolutionTime();

	/**
	 * Sets the expected resolution time of this adminalert.
	 *
	 * @param expectedResolutionTime the expected resolution time of this adminalert
	 */
	public void setExpectedResolutionTime(Date expectedResolutionTime);

	/**
	 * Returns the resolution status of this adminalert.
	 *
	 * @return the resolution status of this adminalert
	 */
	@AutoEscape
	public String getResolutionStatus();

	/**
	 * Sets the resolution status of this adminalert.
	 *
	 * @param resolutionStatus the resolution status of this adminalert
	 */
	public void setResolutionStatus(String resolutionStatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(adminalert adminalert);

	@Override
	public int hashCode();

	@Override
	public CacheModel<adminalert> toCacheModel();

	@Override
	public adminalert toEscapedModel();

	@Override
	public adminalert toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}